# MotionControll.action
# goal
int8 part_id
duration expectedTotalDuration
int16 sequenceSize
body_msgs/PartCommandMsg[] partCommandSequence

---

# result
int8 part_id
duration actualTotalDuration
uint8[] stateOfScenes

---

# feedback
int8 part_id
body_msgs/PartMsg actualCurrentState
duration currentSceneDuration
