# MotionControll.action
# goal
id
body_msgs/PartCommandMsg commmand

---

# result
body_msgs/PartMsg actualFinalState
duration actualTotalDuration

---

# feedback
body_msgs/PartMsg actualCurrentState
duration currentSceneDuration
