# MotionControll.action
# goal
int8 part_id
body_msgs/PartCommandMsg command

---

# result
int8 part_id
body_msgs/PartMsg actualFinalState
duration actualTotalDuration

---

# feedback
int8 part_id
body_msgs/PartMsg actualCurrentState
duration currentSceneDuration
