# MotionControll.action
# goal
jcatty_body_msgs/ServoCommandMsg servoCommand
jcatty_body_msgs/BrushedMotorCommandMsg brushedMotorCommand
jcatty_body_msgs/BrushlessMotorCommandMsg brushlessMotorCommand

---

# result
jcatty_body_msgs/PartMsg finalState
Duration totalDuration

---

# feedback
jcatty_bosdy_msgs/PartMsg currentState
Duration currentSceneDuration
