# rh_info
uint16[3] servo_deg       # [ servo0_deg, servo1_deg, servo2_deg ]
uint8[3] servo_temp       # [ servo0_temp, servo1_temp, servo2_temp ]
uint8[3] servo_current    # [ servo0_current, servo1_current, servo2_current ]
uint8[3] servo_stretch    # [ servo0_stretch, servo1_stretch, servo2_stretch ]
int16 motor_rpm           # second shaft speed (direct encoder's value) in rpm
int16[9] sensor0          #
int16[9] sensor1          #
